# Generated by Django 2.1.5 on 2019-01-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('urgency', models.SmallIntegerField(default=0)),
                ('handled', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
