# Generated by Django 2.1.5 on 2019-01-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='organization',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
