# Generated by Django 2.1.5 on 2019-04-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0004_auto_20190409_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='tempslug', max_length=100),
            preserve_default=False,
        ),
    ]
