# Generated by Django 2.2 on 2019-04-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_site', '0008_auto_20190411_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.CharField(choices=[('PAPER_AIRPLANE', 'Paper Airplane'), ('SQUARE_ROOT', 'Square Root'), ('TETRIS_BLOCK', 'Tetris Block')], max_length=50),
        ),
    ]
